module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "style",
        "perf",
        "refactor",
        "revert",
        "test",
        "docs",
        "chore",
        "workflow",
        "build",
        "ci",
        "mod",
        "wip",
        "types",
        "release",
      ],
    ],
  },
  prompt: {
    scopes: [
      "projects",
      "components",
      "hooks",
      "utils",
      "types",
      "styles",
      "deps",
      "auth",
      "release",
      "other",
    ],
    messages: {
      type: "选择你要提交的类型 :",
      scope: "选择一个提交范围 (可选):",
      customScope: "请输入自定义的提交范围 :",
      subject: "填写简短精炼的变更描述 :\n",
      body: '填写更加详细的变更描述 (可选)。使用 "|" 换行 :\n',
      breaking: '列举非兼容性重大的变更 (可选)。使用 "|" 换行 :\n',
      footerPrefixsSelect: "选择关联issue前缀 (可选):",
      customFooterPrefixs: "输入自定义issue前缀 :",
      footer: "列举关联issue (可选) 例如: #31, #I3244 :\n",
      confirmCommit: "是否提交或修改commit ?",
    },
    types: [
      { value: "feat", name: "feat:       增加新功能" },
      { value: "fix", name: "fix:        修复问题/BUG" },
      { value: "style", name: "style:      代码风格相关无影响运行结果的" },
      { value: "perf", name: "perf:       优化/性能提升" },
      { value: "refactor", name: "refactor:   代码重构" },
      { value: "revert", name: "revert:     撤销修改" },
      { value: "test", name: "test:       测试相关" },
      { value: "docs", name: "docs:       文档/注释" },
      {
        value: "chore",
        name: "chore:      依赖更新/脚手架配置修改等",
      },
      { value: "workflow", name: "workflow:   工作流程改进" },
      {
        value: "build",
        name: "build:      构建流程、外部依赖变更 (如升级 npm 包、修改打包配置等)",
      },
      { value: "ci", name: "ci:         修改 CI 配置、脚本" },
      { value: "mod", name: "mod:        不确定分类的修改" },
      { value: "wip", name: "wip:        正在开发中" },
      { value: "types", name: "types:      类型定义文件修改" },
      { value: "release", name: "release:    发布一个版本" },
    ],
    emptyScopesAlias: "empty:       不填写",
    customScopesAlias: "custom:      自定义",
  },
};
